import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "@/components/custom/Header";
import { Toaster } from "@/components/ui/sonner";

//const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Resume Builder",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ClerkProvider>
            <html lang="en">
                <body>
                    {children}
                    <Toaster />
                </body>
            </html>
        </ClerkProvider>
    );
}
